spring:
  application:
    name: stock-service
server:
  port: 8301

eureka:
  instance:
    hostname: localhost
#    metadata-map:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:8302/eureka}